pipeline {
    agent any

    environment {
        IMAGE_NAME = "yogesh177/team-collab-client"
        IMAGE_TAG = "${BUILD_NUMBER}"

        DEV_SERVER = "35.173.179.185"
        DEV_USER = "ubuntu"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('client') {
                    sh """
                    docker build \
                      -t ${IMAGE_NAME}:${IMAGE_TAG} \
                      -t ${IMAGE_NAME}:develop-latest .
                    """
                }
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {
                    sh '''
                    echo "$DOCKER_PASS" | docker login \
                        -u "$DOCKER_USER" \
                        --password-stdin
                    '''
                }
            }
        }

        stage('Push Image') {
            steps {
                sh """
                docker push ${IMAGE_NAME}:${IMAGE_TAG}
                docker push ${IMAGE_NAME}:develop-latest
                """
            }
        }

        stage('Deploy To Dev') {
            when {
                branch 'develop'
            }

            steps {
                sshagent(['dev-server-key']) {

                    sh """
                    ssh -o StrictHostKeyChecking=no ${DEV_USER}@${DEV_SERVER} '

                        docker pull ${IMAGE_NAME}:develop-latest

                        docker stop frontend || true
                        docker rm frontend || true

                        docker run -d \
                            --name frontend \
                            -p 80:80 \
                            ${IMAGE_NAME}:develop-latest
                    '
                    """
                }
            }
        }
    }

    post {
        always {
            sh 'docker logout || true'
        }
    }
}